### ISSUE TITLE
Неможливо змінити масштаб карти мишею

### ISSUE THREAD

**Issue by int-ua** [osm-ua/openstreetmap.org.ua#5]
Навіть при розгортанні на весь екран. Про причини здогадуюсь, але тим не менш, це досить незручно, на жаль.

**Comment by Andygol** [comment]
@int-ua 
Для увімкнення/вимкнення зміни масштабу мишею достатньо клікнути на мапу

**Comment by int-ua** [comment]
Дякую, дещо неочевидно :)

**Comment by Edward17** [comment]
@int-ua 
edward17.github.io/startbootstrap-modern-business/
